language: node_js
dist: trusty
sudo: false
node_js:
  - v4.0.0
  - lts/argon
  - lts/boron
  - lts/carbon
  - stable
script:
  - npm run coverage
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
