language: node_js
node_js:
  - lts/boron
  - lts/carbon
  - lts/dubnium
  - stable
script: npm run coverage
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
jobs:
  include:
    - stage: Lint
      script: npm run lint
      node_js: lts/carbon
      after_script: skip
