name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron:  0 9 * * 1-5

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run lint

  test:
    name: Node Tests + Coverage
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.0.0
          - 12
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run coverage
      - env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npx codecov

  test-nightly:
    name: Node Nightly Tests + Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm run coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly/ nvm install node
          npm install
          npm run coverage
          npx codecov

  test-electron:
    name: Electron - Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        electron-version:
          - 6.0.0
          - 6
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npx xvfb-maybe npx electron@${{ matrix.electron-version }} ./test/electron

  oidc-conformance:
    name: OIDC Conformance Suite
    runs-on: ubuntu-latest
    needs:
      - test
      - test-electron
    strategy:
      fail-fast: false
      matrix:
        script:
          - basic
          - config
          - dynamic
          - id_token-implicit
          - id_token+token-implicit
          - code+id_token-hybrid
          - code+token-hybrid
          - code+id_token+token-hybrid
          - non-profile
    steps:
      - run: |
          docker pull panvafs/oidc-certification-rp-ci
          docker run -d -p 8080:8080 panvafs/oidc-certification-rp-ci
          while ! curl -sk https://127.0.0.1:8080 >/dev/null; do sleep 2; done
          cd .. && rm -rf oidctest
      - run: git clone https://github.com/panva/openid-client-conformance-tests.git .
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm install panva/node-openid-client#${{ github.sha }}
      - run: npm run ${{ matrix.script }}
        env:
          ISSUER: https://localhost:8080
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          CI: true
